---
###PiHole Playbook.
- name: Pi_Hole Playbook.
  hosts: all
  gather_facts: true
  become: true
  become_method: sudo  


  roles:
    - pi_role

  tasks:
  
    - name: Reminder!
      debug:
        msg: 
         - 'Remember changing your Admin Password: sudo pihole -a -p'